version: '3'
services:
  server:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080  
  
  postgres:
    container_name: postgres
    restart: always
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: DB
    